# conda env create -f conda-env-mac.yml -n tensorflow

name: tensorflow
 
dependencies:
    - python=3.9
    - pip
    - apple::tensorflow-deps==2.5.0
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pip:
        - tensorflow-macos==2.5.0
        - tensorflow-metal==0.1.2